
Parameters:
  GitBranch:
    Type: String
    Description: GitHub repository branch

Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      RoleName: !Sub 'AccountManager-${GitBranch}-CodePipelineServiceRole'
      Policies:
        - PolicyName: CodePipelineServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - acm:DeleteCertificate
                  - acm:Describe*
                  - acm:RequestCertificate
                Resource: !Sub 'arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/*'
              - Effect: Allow
                Action:
                  - codebuild:BatchGetProjects
                Resource: '*'
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:DeleteProject
                  - codebuild:StartBuild
                  - codebuild:UpdateProject
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/AccountManager*'
              - Effect: Allow
                Action:
                  - codepipeline:DeletePipeline
                  - codepipeline:Get*
                  - codepipeline:Update*
                Resource: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:AccountManager-${GitBranch}*'
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                  - codestar-connections:PassConnection
                Resource: '*'
              - Effect: Allow
                Action:
                  - cloudformation:Describe*
                  - cloudformation:UpdateStack
                Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AccountManager*'
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:Create*
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:DeleteSecurityGroup
                  - ec2:RevokeSecurityGroupEgress
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:Describe*
                  - elasticloadbalancing:Create*
                  - elasticloadbalancing:DeleteTargetGroup
                  - elasticloadbalancing:RegisterTargets
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DeleteLoadBalancer
                Resource: !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:loadbalancer/app/AccountManagerLoadBalancer*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DeleteListener
                Resource: !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/AccountManagerLoadBalancer*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:ModifyTargetGroup
                Resource: !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/AccountManagerLambdaTargetGroup*'
              - Effect: Allow
                Action:
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:Get*
                  - iam:PassRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:PutRolePolicy
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/AccountManager*'
              - Effect: Allow
                Action:
                  - lambda:Delete*
                  - lambda:Get*
                  - lambda:Add*
                  - lambda:Remove*
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:AccountManager'
              - Effect: Allow
                Action:
                  - route53:Create*
                  - route53:List*
                  - route53:DeleteHostedZone
                  - route53:Get*
                  - route53:ChangeResourceRecordSets
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::accountmanager-${GitBranch}-pipeline-artifacts-bucket/*'
                  - !Sub 'arn:aws:s3:::accountmanager-${GitBranch}-pipeline-artifacts-bucket'
              - Effect: Allow
                Action:
                  - ssm:Get*
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/AccountManager/*'

Outputs:

  CodePipelineServiceRole:
    Description: The service role used for codepipeline
    Value:
      Ref: CodePipelineServiceRole
    Export:
       Name: !Sub 'AccountManager-${GitBranch}-CodePipelineServiceRole'